export * from "./auth";
export * from "../modules/users/dto/users.dto";
export * from "./dtos/products";
export * from "./dtos/transactions";
export * from "../modules/categories/dto/categories.dto";
export * from "../modules/brands/dto/brands.dto";
export * from "../modules/suppliers/dto/suppliers.dto";
export * from "../modules/branches/dto/branches.dto";
export * from "../modules/customers/dto/customers.dto";
export * from "./dtos/stock";
export * from "../modules/tables/dto/tables.dto";
export * from "../modules/order-queues/dto/order-queues.dto";
export * from "./dtos/table-orders";
export * from "../modules/settings/dto/settings.dto";
export * from "../modules/promotions/dto/promotions.dto";
export * from "../modules/shifts/dto/shifts.dto";
export * from "../modules/bundles/dto/bundles.dto";
export * from "../modules/recipes/dto/recipes.dto";
export * from "../modules/modifiers/dto/modifiers.dto";
export * from "../modules/expenses/dto/expenses.dto";
export * from "../modules/debts/dto/debts.dto";
export * from "./dtos/returns";
export * from "./dtos/purchases";
export * from "./dtos/goods-receipts";
export * from "../modules/points/dto/points.dto";
export * from "../modules/roles/dto/roles.dto";
export * from "./dtos/closing-reports";
export * from "./dtos/stock-transfers";
export * from "./dtos/stock-opname";
export * from "./dtos/product-extensions";
export * from "./dtos/product-variants";
export * from "./dtos/product-branch-skus";
export * from "../modules/vouchers/dto/vouchers.dto";
export * from "../modules/gift-cards/dto/gift-cards.dto";
export * from "../modules/audit-logs/dto/audit-logs.dto";
export * from "./dtos/accounting";
export * from "./dtos/accounting-periods";
export * from "./dtos/accounting-reports";
export * from "./dtos/bank-reconciliation";
export * from "./dtos/recurring-journals";
export * from "./dtos/reports";
export * from "./dtos/cashier";
export * from "../modules/dashboard/dto/dashboard.dto";
export * from "../modules/employee-schedules/dto/employee-schedules.dto";
export * from "../modules/plans/dto/plans.dto";
export * from "../modules/sales-targets/dto/sales-targets.dto";
export * from "../modules/subscriptions/dto/subscriptions.dto";
export * from "../modules/platform-subscriptions/dto/platform-subscriptions.dto";
export * from "../modules/platform-dashboard/dto/platform-dashboard.dto";
export * from "../modules/platform-notifications/dto/platform-notifications.dto";
export * from "../modules/notifications/dto/notifications.dto";
export * from "../modules/pos-activity/dto/pos-activity.dto";
export * from "../modules/register/dto/register.dto";
export * from "../modules/whatsapp-receipt/dto/whatsapp-receipt.dto";
export * from "../modules/whatsapp-chatbot/dto/whatsapp-bot.dto";
export * from "../modules/inventory-forecast/dto/inventory-forecast.dto";
export * from "../modules/installments/dto/installments.dto";
export * from "../modules/me/dto/me.dto";
export * from "../modules/ai-assistant/dto/ai-assistant.dto";
export * from "../modules/profit-dashboard/dto/profit-dashboard.dto";
export * from "./dtos/analytics";
export * from "../modules/auto-journal/dto/auto-journal.dto";
export * from "../modules/vehicles/dto/vehicle.dto";
export * from "../modules/service-orders/dto/service-order.dto";
export * from "../modules/bookings/dto/bookings.dto";
export * from "../modules/racks/dto/racks.dto";

export type ApiSuccess<T> = { data: T };

export type ApiError = {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
};

export type ApiResponse<T> = ApiSuccess<T> | ApiError;

export type PaginatedResult<T> = {
  items: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
};
